# Generated by Django 3.0.7 on 2020-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_describtion', models.TextField(max_length=120)),
                ('book_photo', models.ImageField(upload_to='')),
                ('book_link', models.CharField(max_length=40)),
                ('body_text', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
