# Generated by Django 3.0.7 on 2020-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200622_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_download_link',
            field=models.CharField(default='/', max_length=200),
            preserve_default=False,
        ),
    ]
