# Generated by Django 3.0.7 on 2020-06-22 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200622_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 6, 22, 12, 32, 26, 709058, tzinfo=utc)),
        ),
    ]
