# Generated by Django 3.0.7 on 2020-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200625_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
