# Generated by Django 3.0.7 on 2020-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200625_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
