# Generated by Django 3.0.7 on 2020-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200627_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
