# Generated by Django 3.0.7 on 2020-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category1',
            field=models.CharField(blank=True, choices=[('book', 'book'), ('record', 'records'), ('lecture', 'lecture')], default='book', max_length=40),
        ),
    ]
