# Generated by Django 3.0.7 on 2020-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(blank=True, choices=[('books', 'books'), ('records', 'records'), ('lectures', 'lectures')], default='book', max_length=40),
        ),
    ]
