# Generated by Django 3.0.7 on 2020-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
