# Generated by Django 3.0.7 on 2020-07-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_download_link',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader_paypal_email',
            field=models.CharField(blank=True, default='email', max_length=120),
        ),
    ]
