# Generated by Django 3.0.7 on 2020-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200710_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, default='static/logo.jpg', upload_to='images/'),
        ),
    ]
