# Generated by Django 3.0.7 on 2020-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200712_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploader_paypal_email',
            field=models.CharField(max_length=120),
        ),
    ]
