# Generated by Django 3.0.7 on 2020-07-24 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200712_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_describtion',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 4, 24, 47, 585138, tzinfo=utc), null=True),
        ),
    ]
